version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123456
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 123456 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Java Web Application
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-website
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_NAME=PersonalWebsite
      - DB_USERNAME=sa
      - DB_PASSWORD=123456
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlserver_data:
    driver: local