services:
  - type: web
    name: personal-website
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"